/**
 * Waggle topic library.
 *
 * Add more topics by pushing strings into an existing category's array,
 * or add a whole new category by adding a new "Category Name": [ ... ] entry.
 * Every category should stay above ~25 topics so re-rolls don't repeat too soon.
 */
const WAGGLE_TOPICS = {
  "Gratitude": [
    "A person who changed your life for the better, and why.",
    "A skill or ability you're grateful to have.",
    "A small daily comfort you often take for granted.",
    "A challenge that, in hindsight, you're grateful for.",
    "A place that has given you real peace or comfort.",
    "Someone who believed in you before you believed in yourself.",
    "A piece of technology that has genuinely improved your life.",
    "A lesson a failure taught you that you're now thankful for.",
    "A memory with family that still makes you smile.",
    "Something about your health you don't thank enough.",
    "A stranger's small act of kindness you still remember.",
    "A book, film, or song that arrived at exactly the right time.",
    "A tradition or ritual you're grateful your family kept.",
    "An opportunity you almost didn't take.",
    "Something about where you grew up that you now appreciate.",
    "A teacher or mentor who shaped who you are.",
    "A pet or animal that has brought you joy.",
    "A part of your daily routine you'd genuinely miss if it were gone.",
    "A time someone forgave you.",
    "A freedom you have that you rarely think about.",
    "Something you own that has more sentimental than material value.",
    "A season or type of weather you're grateful for.",
    "A conversation that shifted your perspective for the better.",
    "Something your body lets you do that you don't thank it for.",
    "A community or group you're glad to be part of.",
    "A hard year that ended up teaching you something valuable.",
    "Someone who has quietly supported you without asking for credit.",
    "A meal or food memory that fills you with gratitude.",
    "Something about today, specifically, that's worth being thankful for.",
    "A version of yourself from the past you're grateful you're not anymore."
  ],
  "Personal Growth": [
    "A fear you've overcome, and how.",
    "A habit you're currently trying to build or break.",
    "A belief you held strongly that you've since changed your mind about.",
    "The most useful piece of criticism you've ever received.",
    "A moment you realized you'd matured.",
    "Something you're better at now than you were a year ago.",
    "A comfort zone you'd like to step outside of.",
    "A mistake that taught you more than any success has.",
    "How you handle failure differently now than you used to.",
    "A quality in someone else you'd like to develop in yourself.",
    "The hardest thing you've had to forgive yourself for.",
    "A time you had to unlearn something.",
    "What \"success\" means to you today versus five years ago.",
    "A pattern in your life you keep repeating and want to change.",
    "Something you do now that your younger self would be surprised by.",
    "A boundary you've learned to set.",
    "How you've learned to handle stress better.",
    "A time discipline paid off in an unexpected way.",
    "Something you used to be ashamed of that you've made peace with.",
    "A skill you wish you'd started learning earlier.",
    "How your definition of confidence has changed.",
    "A time you had to be your own source of motivation.",
    "What you do differently after a setback now.",
    "A part of your identity you're still figuring out.",
    "Advice you'd give to yourself exactly one year ago.",
    "A time you chose growth over comfort.",
    "Something you're proud of that no one else noticed.",
    "A limiting belief you're actively working to dismantle.",
    "How you've grown in the way you handle conflict.",
    "A habit of someone you admire that you've tried to adopt."
  ],
  "Current Events": [
    "A recent news story that changed how you think about something.",
    "How technology is reshaping a part of everyday life right now.",
    "A social or cultural shift you've noticed in the past year.",
    "An issue you think gets too little media attention.",
    "A piece of news that made you hopeful recently.",
    "How you decide which news sources to trust.",
    "A local issue in your community worth more attention.",
    "How social media has changed public conversation, for better or worse.",
    "A global challenge you find yourself thinking about often.",
    "An industry you think is changing faster than people realize.",
    "A law or policy change you have strong feelings about.",
    "How your generation views the world differently from the one before it.",
    "A trend you think is overhyped.",
    "A trend you think is underrated.",
    "Something happening in science right now that excites you.",
    "How current events have affected your daily decisions.",
    "A public figure whose recent actions you've been thinking about.",
    "The environmental issue that concerns you most right now.",
    "How you stay informed without feeling overwhelmed.",
    "A shift in the way people work that you've noticed recently.",
    "Something about the economy that affects your life directly.",
    "A cultural debate you find yourself torn on.",
    "How AI is showing up in your daily life lately.",
    "A piece of misinformation you've seen spread recently.",
    "An event this year you think people will still be talking about in a decade.",
    "How your city or region has changed in recent years.",
    "A cause you've become more passionate about recently.",
    "Something in the news that made you angry, and why."
  ],
  "Hypotheticals": [
    "If you could instantly master one skill, what would it be and why?",
    "If you had to move to a new country tomorrow, where would you go?",
    "If you could relive one day of your life exactly as it happened, which would you choose?",
    "If money were no object, how would you spend your time?",
    "If you could have dinner with anyone, living or dead, who would it be?",
    "If you could only keep five possessions, what would they be?",
    "If you woke up with the ability to read minds, what would you do first?",
    "If you had to teach a class on any subject tomorrow, what would you teach?",
    "If you could live in any decade, which would you choose?",
    "If you could send a message to yourself ten years ago, what would it say?",
    "If you had an extra hour every day, how would you use it?",
    "If you could switch lives with anyone for a week, who would it be?",
    "If you could instantly become fluent in any language, which would you pick?",
    "If you had to give up one of your senses, which could you live without most easily?",
    "If you could ask a fortune teller one question, what would it be?",
    "If your life were a movie, what genre would it be?",
    "If you could eliminate one household chore forever, which would it be?",
    "If you had to survive a year on a deserted island with three items, what would you bring?",
    "If you could time travel but never return, would you go to the past or the future?",
    "If you could redesign your hometown, what's the first thing you'd change?",
    "If you had to change careers overnight, what would you choose?",
    "If you could witness any historical event firsthand, which would it be?",
    "If you found a wallet with $1,000 and no ID, what would you do?",
    "If you could have any superpower for just one day, what would you do with it?",
    "If you had to delete every app on your phone except three, which would you keep?",
    "If you could ask your future self one question, what would it be?",
    "If you were guaranteed to succeed at anything, what would you attempt?",
    "If you could pause time for everyone but yourself, what would you do?",
    "If you had to live without the internet for a month, how would your life change?",
    "If you could give every person one piece of advice, what would it be?"
  ],
  "Creative/Imagination": [
    "Describe a world where gravity worked differently.",
    "Invent a new holiday and explain how it's celebrated.",
    "Describe your ideal home if you could design it from scratch.",
    "Invent a gadget that would make daily life easier and describe it.",
    "Describe a color to someone who has never been able to see.",
    "Imagine a conversation between two objects in your house.",
    "Design an animal that's a mix of your three favorite animals.",
    "Describe a city that exists entirely underwater.",
    "Invent a new sport and explain its rules.",
    "Imagine you could design a theme park. What's its theme?",
    "Describe the most interesting dream you can remember.",
    "Invent a myth to explain something in nature.",
    "Describe a place that exists only in your imagination.",
    "If you wrote a novel, what would the opening line be?",
    "Design a restaurant with a completely unique concept.",
    "Imagine a museum exhibit about your own life.",
    "Describe what music would look like if you could see it.",
    "Invent a new word and define what it means.",
    "Imagine a machine that could translate animal sounds. What would your pet say?",
    "Describe a festival celebrated on the moon.",
    "If you could paint using only sound, what would today sound like?",
    "Design a piece of clothing that changes with your mood.",
    "Imagine a library where books write themselves.",
    "Describe a world where everyone can fly, but only backwards.",
    "Invent a tradition your future family will carry on.",
    "Imagine your life as a video game. What's the tutorial level like?",
    "Describe a city built entirely inside a giant tree.",
    "If emotions had weather patterns, what would happiness look like?"
  ],
  "Relationships": [
    "Someone who taught you what real friendship looks like.",
    "A relationship in your life that has changed you the most.",
    "How you show someone you care without saying it directly.",
    "A time you had to rebuild trust with someone.",
    "What you value most in a close friend.",
    "A difficult conversation you're glad you had.",
    "How your relationship with your family has evolved over time.",
    "Someone you've lost touch with that you think about often.",
    "A time you had to set a boundary with someone you love.",
    "What makes you feel truly understood by another person.",
    "A misunderstanding that taught you something about communication.",
    "How you've learned to apologize better.",
    "A relationship you had to let go of, and what it taught you.",
    "Someone who has shown up for you unconditionally.",
    "How you balance independence and closeness in relationships.",
    "A quality you look for in the people you keep close.",
    "A time someone's honesty was hard to hear but helped you.",
    "How you maintain long-distance relationships.",
    "Something you wish you'd said to someone sooner.",
    "A person who challenges you to be better.",
    "How you've changed the way you handle conflict with loved ones.",
    "A friendship that has lasted through very different life stages.",
    "What trust means to you in a relationship.",
    "A time you had to forgive someone who didn't apologize.",
    "How you show love differently to different people in your life.",
    "A moment you felt truly connected to another person.",
    "Something you've learned about yourself through your relationships.",
    "How you decide who deserves a second chance."
  ],
  "Career/Ambition": [
    "A career goal you're currently working toward.",
    "A job or project that taught you the most about yourself.",
    "What \"doing meaningful work\" means to you.",
    "A skill you want to develop in the next year.",
    "A risk you took in your career that paid off, or didn't.",
    "What motivates you on hard workdays.",
    "A mentor or colleague who shaped how you work.",
    "How you define success in your career, beyond money or title.",
    "A career path you considered but didn't pursue.",
    "What you'd do for work if money weren't a factor.",
    "A professional failure that taught you something valuable.",
    "How your ambitions have changed since you started working.",
    "A work habit you're proud of.",
    "Something about your industry you wish more people understood.",
    "A goal you set for yourself that you actually achieved.",
    "How you handle burnout or overwhelm at work.",
    "A skill from outside your field that has helped your career.",
    "What you look for in a workplace or team.",
    "A time you had to advocate for yourself professionally.",
    "Where you'd like your career to be in five years.",
    "A piece of career advice you'd give your younger self.",
    "How you balance ambition with contentment.",
    "A project you're proud of that most people don't know about.",
    "What leadership means to you.",
    "A moment you felt genuinely proud of your work.",
    "How you decide when it's time to move on from something.",
    "A fear related to your career that you're working through.",
    "What \"growth\" looks like for you professionally right now."
  ]
};

// Node/CommonJS export guard (unused in the browser, harmless if present).
if (typeof module !== "undefined" && module.exports) {
  module.exports = WAGGLE_TOPICS;
}
